// src/app/pages/web-programming/web-programming.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-web-programming',
  templateUrl: './web-programming.component.html',
  styleUrls: ['./web-programming.component.scss']
})
export class WebProgrammingComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container" style="padding: 0px">
    <Card name="Internet Based Computing">
        <div class="container-fluid col-xs-12 text-left">
            <p>
                Internet Based Computer started my journey with web technologies. It helped me learn the basics of HTML, CSS, and JavaScript.
                A lot of the assignments were pretty basic web design activities, later in the semester we got into learning JavaScript. To end
                off the semester, we began learning Java Swing, and I got my first taste of using NetBeans.
            </p>
            <h3><a href="http://emunix.emich.edu/~haynes/231/wi15/">Course Website</a></h3>
            <h3>Projects</h3>
            <ol type="1">
                <li>
                    Project 1 - Painting Mosaic
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp1.html">pp1.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp1.css">pp1.css</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 2 - Slide Show
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp2.html">pp2.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp2.css">pp2.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/.js">pp2.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 3 - Move a Sprite
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.html">pp3.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.css">pp3.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.js">pp3.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 4 - Monsters and Gold!
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.html">pp4.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.css">pp4.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.js">pp4.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 5 - Multi-threaded Java App
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/lab0408.java">lab0408.java</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 6 - Speed Reading GUI
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/speedReaderUI.java">speedReaderUI.java</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/text.txt">text.txt</a>
                        </li>
                    </ol>
                </li>
            </ol>
            <h3>Labs</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/lab0112.html">Lab 01/12 - Double Dactyl Table</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0114.html">Lab 01/14 - Image Map</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0126-internal.html">Lab 01/26 (Using Internal CSS)</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0126-in-line.html">Lab 01/26 (Using In Line CSS)</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0128.html">Lab 01/28 - Mondrian Art</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0209.html">Lab 02/09 - Add/Subtract</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0209a.html">Lab 02/09 - Mondrian Color Switch</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0211.html">Lab 02/11 - JS Arithmetic Training</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0216.html">Lab 02/16 - Explosion Timer</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/labJack.html">Lab 03/02 - Jumping Jack</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/labJan.html">Lab 03/02 - Flood It</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0304.html">Lab 03/04 - Pop Up DOM Surgery</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0309.html">Lab 03/09 - RegEx JS Ident &amp; Emoticon</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0311.html">Lab 03/11 - Zip Code</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0316.html">Lab 03/16 - DOM Surgery Drag &amp; Drop</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0323.html">Lab 03/23 - DOM Surgery Pop Up Button</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0325.html">Lab 03/25 - JSHint &amp; Fibonancci Trace</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0401.java">Lab 04/01 - Cuboid GUI Calculator</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0406.java">Lab 04/06 - Phone GUI</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0408.java">Lab 04/08 - Multithreading App</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/speedReaderUI.java">Lab 04/13 - Speed Reader GUI</a>
                </li>
            </ol>
            
            
            <br />
            <h3>Notes</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes011215.html">01/12 - Ordered Lists and Basic Forms</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0114.html">01/14 - More Forms and Image Mapping</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0126.html">01/26 - CSS</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0128.html">01/28 - CSS</a> 
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0204.html">02/04 - CSS Positioning and Intro to JavaScript</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0209.html">02/09 - JavaScript for Loop and Changing Styles</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0216.html">02/16 - Timers</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0304.html">03/04 - JavaScript &amp; HTML DOM</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0309.html">03/09 - Regular Expressions</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0311.html">03/11 - Regular Expressions</a>
                </li>
            </ol>
            
            <br />
            <h3>Extra Stuff</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/chaudhuri_homepage-remake.html">Professor Chaudhuri's Homepage Remake</a>
                </li>
            </ol>
        </div>
    </Card>
</div>

// src/lib/pages/web-programming.svelte
<script>
    import Card from '../../card.svelte';
</script>

<div class="container" style="padding:0px">
    <Card name="Internet Based Computing">
        <div class="container-fluid col-xs-12 text-left">
            <p>
                Internet Based Computer started my journey with web technologies. It helped me learn the basics of HTML, CSS, and JavaScript.
                A lot of the assignments were pretty basic web design activities, later in the semester we got into learning JavaScript. To end
                off the semester, we began learning Java Swing, and I got my first taste of using NetBeans.
            </p>
            <h3><a href="http://emunix.emich.edu/~haynes/231/wi15/">Course Website</a></h3>
            <h3>Projects</h3>
            <ol type="1">
                <li>
                    Project 1 - Painting Mosaic
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp1.html">pp1.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp1.css">pp1.css</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 2 - Slide Show
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp2.html">pp2.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp2.css">pp2.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/.js">pp2.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 3 - Move a Sprite
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.html">pp3.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.css">pp3.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp3.js">pp3.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 4 - Monsters and Gold!
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.html">pp4.html</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.css">pp4.css</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/Projects/pp4.js">pp4.js</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 5 - Multi-threaded Java App
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/lab0408.java">lab0408.java</a>
                        </li>
                    </ol>
                </li>
                <br />
                <li>
                    Project 6 - Speed Reading GUI
                    <ol type="A">
                        <li>
                            <a href="https://kszalai.github.io/231/speedReaderUI.java">speedReaderUI.java</a>
                        </li>
                        <li>
                            <a href="https://kszalai.github.io/231/text.txt">text.txt</a>
                        </li>
                    </ol>
                </li>
            </ol>
            <h3>Labs</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/lab0112.html">Lab 01/12 - Double Dactyl Table</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0114.html">Lab 01/14 - Image Map</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0126-internal.html">Lab 01/26 (Using Internal CSS)</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0126-in-line.html">Lab 01/26 (Using In Line CSS)</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0128.html">Lab 01/28 - Mondrian Art</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0209.html">Lab 02/09 - Add/Subtract</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0209a.html">Lab 02/09 - Mondrian Color Switch</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0211.html">Lab 02/11 - JS Arithmetic Training</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0216.html">Lab 02/16 - Explosion Timer</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/labJack.html">Lab 03/02 - Jumping Jack</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/labJan.html">Lab 03/02 - Flood It</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0304.html">Lab 03/04 - Pop Up DOM Surgery</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0309.html">Lab 03/09 - RegEx JS Ident &amp; Emoticon</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0311.html">Lab 03/11 - Zip Code</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0316.html">Lab 03/16 - DOM Surgery Drag &amp; Drop</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0323.html">Lab 03/23 - DOM Surgery Pop Up Button</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0325.html">Lab 03/25 - JSHint &amp; Fibonancci Trace</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0401.java">Lab 04/01 - Cuboid GUI Calculator</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0406.java">Lab 04/06 - Phone GUI</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/lab0408.java">Lab 04/08 - Multithreading App</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/speedReaderUI.java">Lab 04/13 - Speed Reader GUI</a>
                </li>
            </ol>
            
            
            <br />
            <h3>Notes</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes011215.html">01/12 - Ordered Lists and Basic Forms</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0114.html">01/14 - More Forms and Image Mapping</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0126.html">01/26 - CSS</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0128.html">01/28 - CSS</a> 
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0204.html">02/04 - CSS Positioning and Intro to JavaScript</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0209.html">02/09 - JavaScript for Loop and Changing Styles</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0216.html">02/16 - Timers</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0304.html">03/04 - JavaScript &amp; HTML DOM</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0309.html">03/09 - Regular Expressions</a>
                </li>
                <li>
                    <a href="https://kszalai.github.io/231/inlabnotes0311.html">03/11 - Regular Expressions</a>
                </li>
            </ol>
            
            <br />
            <h3>Extra Stuff</h3>
            <ol type="1">
                <li>
                    <a href="https://kszalai.github.io/231/chaudhuri_homepage-remake.html">Professor Chaudhuri's Homepage Remake</a>
                </li>
            </ol>
        </div>
    </Card>
    <i>*This page exists for historical purposes, and also to let me play with my own routing in Svelte!</i> 😁
</div>
