// src/lib/work/work-history.svelte
<script>
    export let position;
    export let company;
    export let location;
    export let startTime;
    export let endTime = "Present";
</script>

<div class="col-xs-12 text-left">
    <h3>{position}, {company}</h3>
    <h5>{location} {startTime} - {endTime}</h5>
    <ul>
        <slot></slot>
    </ul>
</div>

// src/app/work/work-history/work-history.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'WorkHistory',
  templateUrl: './work-history.component.html',
  styleUrls: ['./work-history.component.scss']
})
export class WorkHistoryComponent implements OnInit {

  @Input() position: string = "";
  @Input() company: string = "";
  @Input() location: string = "";
  @Input() startTime: string = "";
  @Input() endTime: string = "Present";

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="col-xs-12 text-left">
    <h3>{{position}}, {{company}}</h3>
    <h5>{{location}} ({{startTime}} - {{endTime}})</h5>
    <ul>
        <ng-content></ng-content>
    </ul>
</div>
