// src/app/info-header/info-header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'InfoHeader',
  templateUrl: './info-header.component.html',
  styleUrls: ['./info-header.component.scss']
})
export class InfoHeaderComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container">
    <div class="col-xs-12 card">
        <div class="col-xs-4">
            <img class="profile_pic pull-right" src="../../assets/profile_pic.jpg" alt="Kyle Szalai"/>
        </div>
        <div class="col-xs-8 profile_card">
            <h1>Kyle Szalai</h1>
            Software Engineer
            <br />
            Eastern Michigan University Alumni
            <br />
            <a title="Send me an email!" href="mailto:kyleszalai@gmail.com">kyleszalai@gmail.com</a>
            <br />
            <div class="social">
                <a href="https://github.com/kszalai"><i class="fa fa-github fa-2x"></i></a>
                <a href="https://www.linkedin.com/in/kyle-szalai-41649bb3"><i class="fa fa-linkedin fa-2x"></i></a>
            </div>
        </div>
    </div>
</div>

// src/info-header.svelte
<script lang="ts">
    import profilePic from './assets/profile_pic.jpg';
</script>

<div class="container">
    <div class="col-xs-12 card">
        <div class="col-xs-4">
            <img class="profile_pic pull-right" src={profilePic} alt="Kyle Szalai"/>
        </div>
        <div class="col-xs-8 profile_card">
            <h1>Kyle Szalai</h1>
            Software Engineer
            <br />
            Eastern Michigan University Alumni
            <br />
            <a title="Send me an email!" href="mailto:kyleszalai@gmail.com">kyleszalai@gmail.com</a>
            <br />
            <div class="social">
                <a href="https://github.com/kszalai"><i class="fa fa-github fa-2x"></i></a>
                <a href="https://www.linkedin.com/in/kyle-szalai-41649bb3"><i class="fa fa-linkedin fa-2x"></i></a>
            </div>
        </div>
    </div>
</div>
